# Generated by Django 5.1.4 on 2026-03-30 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Action performed, e.g. 'login', 'logout', 'create_report', 'update_report', 'delete_report', 'create_finding', 'update_finding', 'delete_finding', 'create_kb_entry', 'update_kb_entry', 'delete_kb_entry', 'update_user_role', 'activate_user', 'deactivate_user'.", max_length=100)),
                ('object_type', models.CharField(help_text="Type of object affected, e.g. 'report', 'finding', 'kb_entry', 'user', 'session'.", max_length=100)),
                ('object_id', models.CharField(blank=True, default='', help_text='Primary key of the affected object.', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context (never include sensitive data).')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
